# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_auto_20160823_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='uuid',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
